name: tox-on-push
on: push

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup python using ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with tox
        run: |
          tox -e lint
      - name: Test
        run: |
          tox
